### ISSUE TITLE
How to run This ??

### ISSUE THREAD

**Issue by ssoad** [HtewechIheb/Scientific-Calculator-Syntax-Parser#1]

**Comment by HtewechIheb** [comment]
In order to run this program, follow these steps under a UNIX environment:

- Install Flex
- Install Bison
- Run the following commands:
`
flex calculator.flex
`
`
bison -d calculator.y
`
`
gcc -o calculator lex.yy.c calculator.tab.c -lfl -lm
`
`
 ./calculator
`

**Comment by ssoad** [comment]
Thanks
